export enum Role {
  USER = 'USER',
  ADMIN = 'ADMIN',
}

export enum ListingStatus {
  PENDING = 'PENDING',
  ACTIVE = 'ACTIVE',
  UNLOCKED = 'UNLOCKED',
  CONFIRMED = 'CONFIRMED',
  COMPLETED = 'COMPLETED',
  DELETED = 'DELETED',
  REJECTED = 'REJECTED',
}

export enum ListingHouseType {
  STUDIO = 'STUDIO',
  BEDSITTER = 'BEDSITTER',
  ONE_BEDROOM = 'ONE_BEDROOM',
  TWO_BEDROOM = 'TWO_BEDROOM',
  THREE_BEDROOM = 'THREE_BEDROOM',
  FOUR_BEDROOM_PLUS = 'FOUR_BEDROOM_PLUS',
  MANSION = 'MANSION',
}

export enum TransactionStatus {
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
  REFUNDED = 'REFUNDED',
}

export enum TransactionType {
  PURCHASE = 'PURCHASE',
  SPEND = 'SPEND',
  REFUND = 'REFUND',
  BONUS = 'BONUS',
}

export enum CommissionStatus {
  PENDING = 'PENDING',
  DUE = 'DUE',
  PROCESSING = 'PROCESSING',
  PAID = 'PAID',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
}

export enum ConfirmationSide {
  OUTGOING_TENANT = 'OUTGOING_TENANT',
  INCOMING_TENANT = 'INCOMING_TENANT',
}

export enum DisputeStatus {
  OPEN = 'OPEN',
  INVESTIGATING = 'INVESTIGATING',
  RESOLVED = 'RESOLVED',
  CLOSED = 'CLOSED',
}

export enum SupportTicketStatus {
  OPEN = 'OPEN',
  IN_REVIEW = 'IN_REVIEW',
  RESOLVED = 'RESOLVED',
  CLOSED = 'CLOSED',
}

export enum ReviewerSide {
  INCOMING_TENANT = 'INCOMING_TENANT',
  OUTGOING_TENANT = 'OUTGOING_TENANT',
}

export enum ReferralStatus {
  INVITED = 'INVITED',
  JOINED = 'JOINED',
  REWARDED = 'REWARDED',
  EXPIRED = 'EXPIRED',
}
